# dashboard-app-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-app-configmap
data:
  requirements.txt: |
    # Contenido de tus requerimientos, puede ser una lista de paquetes y versiones
    dash==1.21.0
    pandas==1.3.0
    plotly==5.1.0
    # Agrega aquí los paquetes y versiones que necesitas

---

# dashboard-app-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-app
  template:
    metadata:
      labels:
        app: dashboard-app
    spec:
      containers:
        - name: dashboard-app
          image: tu_usuario/tu_imagen:latest
          ports:
            - containerPort: 8050
          volumeMounts:  # Montamos el ConfigMap como un volumen en el contenedor
            - name: requirements-volume
              mountPath: /app/requirements.txt
              subPath: requirements.txt
      volumes:
        - name: requirements-volume
          configMap:
            name: dashboard-app-configmap
            items:
              - key: requirements.txt
                path: requirements.txt

---

# dashboard-app-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: dashboard-app-service
spec:
  selector:
    app: dashboard-app
  ports:
    - protocol: TCP
      port: 80  # Puerto del servicio expuesto en el clúster
      targetPort: 8050  # Puerto al que el servicio redirige el tráfico
  type: LoadBalancer  # Tipo de servicio LoadBalancer para exponer la aplicación al exterior (requiere proveedor de Kubernetes con soporte para LoadBalancer)

